CREATE TABLE IF NOT EXISTS users_rate_tb (
    id SERIAL PRIMARY KEY,
    request_user_id BIGINT NOT NULL UNIQUE,
    rating VARCHAR(9) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
